### ISSUE TITLE
agregar slide con links que usamos

### ISSUE THREAD

**Issue by tlacoyodefrijol** [rodowi/git-aprende#10]

**Comment by defvol** [comment]
:+1: suena muy bien

**Comment by tlacoyodefrijol** [comment]
![2014-08-26](https://cloud.githubusercontent.com/assets/5587545/6083283/ffd153be-adec-11e4-89b8-4dad4a08dcfd.gif)

**Comment by mverarey** [comment]
saludos

**Comment by defvol** [comment]
Voy agregar:

Git
- [x] [El libro de Git (gratuito)](http://git-scm.com/) 
- [x] [Understanding version control](https://training.github.com/kit/foundations/#understanding-version-control)
- [x] [GIT CHEATSHEET](http://ndpsoftware.com/git-cheatsheet.html)  

GitHub
- [x] [Contributing to Open Source on GitHub](https://guides.github.com/activities/contributing-to-open-source/) 
- [x] [Understanding the GitHub Flow](https://guides.github.com/introduction/flow/)  
- [x] [Mastering Issues](https://guides.github.com/features/issues/)
