### ISSUE TITLE
Estaría bien tener un slide con los nombres de la gente que vio el taller

### ISSUE THREAD

**Issue by defvol** [rodowi/git-aprende#12]
Para agregar gente basta con copiar y agregar otro `<li>` con los datos en https://github.com/rodowi/git-aprende/blob/master/index.html#L107

**Comment by pepegarcia** [comment]
pepe_garcia :)

**Comment by defvol** [comment]
Hey @pepegarcia ve el pull request #20 para que veas como puedes agregar tu nombre a la presentación. Es una prueba para ver si le agarraste la onda :)
